services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: tictactoe-backend
    restart: unless-stopped
    environment:
      - FLASK_ENV=production
      - PYTHONUNBUFFERED=1
    networks:
      - tictactoe-network
    # Temporarily disable health check for debugging
    # healthcheck:
    #   test: ["CMD-SHELL", "python -c 'print(\"healthy\")'"]
    #   interval: 30s
    #   timeout: 5s
    #   retries: 3
    #   start_period: 20s

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: tictactoe-frontend
    restart: unless-stopped
    depends_on:
      - backend
    networks:
      - tictactoe-network
    # Temporarily disable health check for debugging
    # healthcheck:
    #   test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/health"]
    #   interval: 30s
    #   timeout: 5s
    #   retries: 3
    #   start_period: 10s

networks:
  tictactoe-network:
    driver: bridge

volumes:
  # Add volumes if needed for persistence
  tictactoe-data: 